spring.application.name=FinanceTracker

# Spring Configuration
spring.main.allow-bean-definition-overriding=true

# Server Configuration
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.ibikmqrigxwtwwhaypdg
spring.datasource.password=gestionFinanciera


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# JWT Configuration
jwt.secret=iT7e9DmPhdyvoWv9hBHgRAxkdwUGmFWIMX6kzMeApak
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# Google OAuth2 Configuration

spring.security.oauth2.client.registration.google.client-id=600899848714-bhgs626e566f3gds1m1g6srckdf6gp9m.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email


# Logging Configuration
logging.level.root=INFO
logging.level.com.udea.FinanceTracker=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

