name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests
        working-directory: ./backend/FinanceTracker

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/personalfinancetracker:latest ./backend/FinanceTracker

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/personalfinancetracker:latest